services:
  - type: web
    name: elderlycareui-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt && mkdir -p backend/logs backend/audio_files
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .
    healthCheckPath: / 