services:
  - type: web
    name: elderlycareui-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt && chmod +x build_render.sh && ./build_render.sh
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: true
      - key: CLOUD_ENV
        value: true
      - key: PORT
        value: 10000
    healthCheckPath: / 